"""Added total_price and status to Order and also a timestamp to orderitem

Revision ID: 2671b32ef3ca
Revises: 7578a67f8377
Create Date: 2026-03-22 15:47:16.010473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '2671b32ef3ca'
down_revision = '7578a67f8377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False, server_default=text('0')))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='PENDING'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('previous_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('previous_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
