"""Add rating and previous_price to Product

Revision ID: 7578a67f8377
Revises: 
Create Date: 2026-03-21 09:26:20.177990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7578a67f8377'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('previous_price')

    # ### end Alembic commands ###
