"""added address,phone, and email to order

Revision ID: 94bfbffd9324
Revises: 2671b32ef3ca
Create Date: 2026-03-29 12:33:23.436085

"""
from email.policy import default

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bfbffd9324'
down_revision = '2671b32ef3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
